[daily_remarks]
prefix = "r "
contents = [
    "守望先锋真好玩",
    "minecraft真好玩",
    "皇室战争真好玩",
    "今天天气真好",
    "没有牺牲大到无法接受",
    "没有背叛小到可以容忍",
    "今天吃自助"
]
generation_chance = 0.8
# [新增] 这里设置为 3，表示将随机生成 1 到 4 行备注
max_lines = 4

[activity_remarks]
contents = [
    "我是备注",
    "我是备注1234",
    "我是备注abcd"
]
generation_chance = 0.5

wake_keywords = [
    "起床",
    "醒",
    "w",
    "wake",
    "新的一天开始了A"
]

common_activities = ["工作", "阅读", "休息"]