# 图表生成器的配置文件

[paths]
# 数据库文件的完整路径
database = "C:/Computer/my_github/github_cpp/time_tracer/my_test/output/time_data.sqlite3"


# 生成图表的输出目录
# 如果留空 ""，将默认输出到程序根目录下的 output 文件夹
output_directory = ""

[settings]
# 您想要生成图表的日期，格式为 "YYYYMMDD"
target_date = "20250101"

[colors]
# 顶级活动分类的颜色映射
study = "#2ECC40"
recreation = "#FF4136"
meal = "#FF851B"
exercise = "#0074D9"
routine = "#AAAAAA"
sleep = "#B10DC9"
code = "#39CCCC"
# 为未在上面定义的活动提供一个默认颜色
default = "#808080"