# --- 文本配置 ---
report_title_label = "Yearly Summary for"

date_range_separator = "to"

actual_days_label = "Actual Days with Records"
total_time_label = "Total Time Recorded"
no_records_message = "No time records found for this year."

invalid_data_message = "Invalid year format or data range."

main_font = "Noto Serif SC"
cjk_main_font = "Noto Serif SC"
base_font_size = 12
report_title_font_size = 18
category_title_font_size = 16
margin_in = 1.0
list_top_sep_pt = 0
list_item_sep_ex = -0.5
