# week/WeekTexConfig.toml

# --- 文本配置 ---
report_title_label = "Weekly Summary for"
date_range_separator = "to"

actual_days_label = "Active Days"
total_time_label = "Total Time"
no_records_message = "No records found for this week."
invalid_data_message = "Invalid week data range."

# --- 样式配置  ---
main_font = "Noto Serif SC"
cjk_main_font = "Noto Serif SC"
base_font_size = 12
report_title_font_size = 18
category_title_font_size = 16
margin_in = 1.0
list_top_sep_pt = 0
list_item_sep_ex = -0.5