# config/config.toml

[system]
error_log = "../output/error_log.txt"
export_root = "exported_reports"
save_processed_output = true
date_check_continuity = true

[converter]
# 指向新的 TOML 格式的转换器配置
interval_config = "converter/interval_processor_config.toml"

[reports.typst]
day = "reports/day/DayTypConfig.toml"
month = "reports/month/MonthTypConfig.toml"

week = "reports/week/WeekTypConfig.toml"
year = "reports/year/YearTypConfig.toml"
recent = "reports/recent/RecentTypConfig.toml"
range = "reports/range/RangeTypConfig.toml"

[reports.latex]
day = "reports/day/DayTexConfig.toml"
month = "reports/month/MonthTexConfig.toml"

week = "reports/week/WeekTexConfig.toml"
year = "reports/year/YearTexConfig.toml"
recent = "reports/recent/RecentTexConfig.toml"
range = "reports/range/RangeTexConfig.toml"

[reports.markdown]
day = "reports/day/DayMdConfig.toml"
month = "reports/month/MonthMdConfig.toml"

week = "reports/week/WeekMdConfig.toml"
year = "reports/year/YearMdConfig.toml"
recent = "reports/recent/RecentMdConfig.toml"
range = "reports/range/RangeMdConfig.toml"